# Generated by Django 5.2.8 on 2025-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='togri_javoblar_soni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='umumiy_savollar_soni',
            field=models.IntegerField(default=0),
        ),
    ]
