# Generated by Django 5.2.8 on 2025-11-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testresult_togri_javoblar_soni_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='jami_ball',
            field=models.IntegerField(default=0, verbose_name='Jami Ball'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='sinov_sanasi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sinov Sanasi'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='Test'),
        ),
    ]
