# Generated by Django 5.2.8 on 2025-11-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='ball',
            field=models.IntegerField(default=1, verbose_name='Savol Bali'),
        ),
    ]
